package com.github.kimuth.jetbrainsmakotemplateplugin.lang

import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.openapi.fileTypes.FileTypeManager
import com.intellij.testFramework.PlatformTestUtil
import com.intellij.testFramework.fixtures.BasePlatformTestCase

/**
 * Annotator tests verifying MakoAnnotator satisfies COMP-03:
 * - Unclosed <%def> produces an ERROR annotation on the <%def opening token
 * - Unclosed <%block> produces an ERROR annotation on the <%block opening token
 * - Well-formed <%def>...</%def> produces no error annotations
 * - Unrecognized directive (<%bogus>) produces an ERROR annotation
 *
 * Tests 1/2/4 use doHighlighting() + targeted message assertions to avoid interference
 * from PSI parse-error highlights that the parser generates for malformed/unclosed tags.
 * Test 3 (well-formed) uses configureByFile + checkHighlighting since the file has no
 * parse errors and the negative assertion (no unexpected errors) is the key invariant.
 */
class MakoAnnotatorTest : BasePlatformTestCase() {

    override fun getTestDataPath(): String = "src/test/testData"

    override fun setUp() {
        super.setUp()
        // Force MakoFileType registration by touching the file type manager.
        // In some test environments, the file type extension is loaded lazily;
        // dispatching all pending EDT events processes any deferred extension registrations.
        FileTypeManager.getInstance().getFileTypeByExtension("mako")
        PlatformTestUtil.dispatchAllInvocationEventsInIdeEventQueue()
    }

    // -------------------------------------------------------------------------
    // Helper: create a .mako file, configure the fixture, run highlighting
    // -------------------------------------------------------------------------

    /**
     * Creates a physical .mako file in the test project and configures the editor fixture.
     * Uses addFileToProject (not configureByText) to ensure MakoFileType is recognised even
     * when the file type extension is registered lazily in the test JVM.
     */
    private fun configureMakoFile(content: String) {
        val file = myFixture.addFileToProject("annotator_test.mako", content)
        myFixture.configureFromExistingVirtualFile(file.virtualFile)
    }

    // -------------------------------------------------------------------------
    // COMP-03: Unclosed <%def> tag
    // -------------------------------------------------------------------------

    /**
     * COMP-03: Unclosed <%def> tag — no closing </%def> present.
     * MakoAnnotator must produce an ERROR annotation with message
     * "Unclosed <%def>: missing closing tag" on the <%def opening token range.
     *
     * Uses doHighlighting() to collect all highlights and filters specifically for
     * the annotator's message, ignoring PSI parse-error highlights generated by the
     * parser when the END_TAG is absent.
     */
    fun testUnclosedDefTagShowsError() {
        configureMakoFile("<%def name=\"foo\">\ncontent\n")
        val highlights = myFixture.doHighlighting()
        val annotatorError = highlights.find {
            it.severity == HighlightSeverity.ERROR &&
                it.description == "Unclosed <%def>: missing closing tag"
        }
        assertNotNull(
            "Expected ERROR annotation 'Unclosed <%def>: missing closing tag' for unclosed <%def> tag",
            annotatorError
        )
    }

    // -------------------------------------------------------------------------
    // COMP-03: Unclosed <%block> tag
    // -------------------------------------------------------------------------

    /**
     * COMP-03: Unclosed <%block> tag — no closing </%block> present.
     * MakoAnnotator must produce an ERROR annotation with message
     * "Unclosed <%block>: missing closing tag" on the <%block opening token range.
     */
    fun testUnclosedBlockTagShowsError() {
        configureMakoFile("<%block name=\"body\">\ncontent\n")
        val highlights = myFixture.doHighlighting()
        val annotatorError = highlights.find {
            it.severity == HighlightSeverity.ERROR &&
                it.description == "Unclosed <%block>: missing closing tag"
        }
        assertNotNull(
            "Expected ERROR annotation 'Unclosed <%block>: missing closing tag' for unclosed <%block> tag",
            annotatorError
        )
    }

    // -------------------------------------------------------------------------
    // COMP-03 negative: Well-formed <%def>...</%def> — no errors
    // -------------------------------------------------------------------------

    /**
     * COMP-03 negative test: Well-formed <%def>...</%def> must produce no error annotations.
     * Uses checkHighlighting() with a fixture file that has no <error> markers — the call
     * verifies that MakoAnnotator does NOT fire for a correctly closed def tag.
     */
    fun testWellFormedDefTagNoError() {
        myFixture.configureByFile("annotator/WellFormedDefTag.mako")
        myFixture.checkHighlighting(true, false, false)
    }

    // -------------------------------------------------------------------------
    // COMP-03: Invalid directive name
    // -------------------------------------------------------------------------

    /**
     * COMP-03: Unrecognized Mako directive (<%bogus>) in template text.
     * MakoAnnotator must produce an ERROR annotation with message
     * "Unknown Mako directive: <%bogus>".
     *
     * The Mako lexer emits '<', '%', and 'bogus attr="x">' as three separate TEMPLATE_TEXT
     * tokens. The annotator detects the pattern by inspecting the '<' node's immediate
     * siblings rather than searching for "<%name" within a single token.
     */
    fun testInvalidDirectiveShowsError() {
        configureMakoFile("<%bogus attr=\"x\">\ncontent\n")
        val highlights = myFixture.doHighlighting()
        val annotatorError = highlights.find {
            it.severity == HighlightSeverity.ERROR &&
                it.description == "Unknown Mako directive: <%bogus>"
        }
        assertNotNull(
            "Expected ERROR annotation 'Unknown Mako directive: <%bogus>' for unrecognized directive",
            annotatorError
        )
    }
}
